BEGIN;
CREATE TABLE IF NOT EXISTS token_blacklist(token TEXT PRIMARY KEY,expires_at TIMESTAMPTZ NOT NULL);CREATE INDEX IF NOT EXISTS idx_token_blacklist_expires ON token_blacklist(expires_at);
CREATE TABLE IF NOT EXISTS retention_tenant_memberships(tenant_id TEXT NOT NULL,user_id BIGINT NOT NULL,role TEXT NOT NULL CHECK(role IN('analyst','data_engineer','data_scientist','retention_manager','admin','viewer')),active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(tenant_id,user_id));
CREATE TABLE IF NOT EXISTS governed_retention_runs(id BIGSERIAL PRIMARY KEY,tenant_id TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN('ingested','featured','scored','reviewed','suppressed','authorized','intervened','measured')),version INTEGER NOT NULL DEFAULT 1,run_data JSONB NOT NULL CHECK(jsonb_typeof(run_data)='object'),idempotency_key TEXT NOT NULL,created_by BIGINT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(tenant_id,idempotency_key));
CREATE TABLE IF NOT EXISTS retention_score_batches(id BIGSERIAL PRIMARY KEY,tenant_id TEXT NOT NULL,run_id BIGINT NOT NULL REFERENCES governed_retention_runs(id),model_version TEXT NOT NULL,records JSONB NOT NULL CHECK(jsonb_typeof(records)='array'),created_by BIGINT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS retention_events(id BIGSERIAL PRIMARY KEY,tenant_id TEXT NOT NULL,run_id BIGINT NOT NULL REFERENCES governed_retention_runs(id),actor_id BIGINT NOT NULL,event_type TEXT NOT NULL,payload JSONB NOT NULL DEFAULT '{}',occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS retention_outbox(id BIGSERIAL PRIMARY KEY,tenant_id TEXT NOT NULL,run_id BIGINT NOT NULL REFERENCES governed_retention_runs(id),provider TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN('pending','processing','succeeded','failed','dead_letter')),attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT,payload JSONB NOT NULL DEFAULT '{}',requested_by BIGINT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS retention_runs_state_idx ON governed_retention_runs(tenant_id,state);CREATE INDEX IF NOT EXISTS retention_outbox_status_idx ON retention_outbox(status,created_at);
COMMIT;
